[custom]
;不要随意改变关键字，否则会导致出错
;ACL4SSR规则
;MoistSoil2474修改版👍👍👍
;Travis0234自用版，原版@ACL4SSR @MoistSoil2474

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持


;设置规则标志位
ruleset=🎯 Direct,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 Direct,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 AdBlock,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 AppAdBlock,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🎯 Direct,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 Direct,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=📢 GoogleFCM,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=Ⓜ️ Bing,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ OneDrive,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ Microsoft,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=✈️ Telegram,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🤖 OpenAI,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🤖 OpenAI,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🎶 NeteaseMusic,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 Steam,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 Steam,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 Steam,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 Steam,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 Steam,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 YouTube,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 Netflix,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📺 Bahamut,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=🌍 GlobalMedias,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=📺 Bilibili,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 Bilibili,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 MediasCN,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🚀 Selector,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 Direct,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 Direct,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 Direct,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 Direct,https://ghfast.top/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 Direct,[]GEOIP,LAN
ruleset=🎯 Direct,[]GEOIP,CN
ruleset=🐟 Final,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 Selector`select`[]♻️ Url-Test`[]🔯 Fallback`[]🔮 LoadBalance`[]🌐 WestData`[]🌸 FlowerCloud`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🌍 Europe`[]☁️ Cloudflare `[]🚀 Switch`[]DIRECT
custom_proxy_group=🚀 Switch`select`.*
custom_proxy_group=♻️ Url-Test`url-test`.*`http://www.gstatic.com/generate_204`600,,25
custom_proxy_group=🔯 Fallback`fallback`.*`http://www.gstatic.com/generate_204`600,,30
custom_proxy_group=🔮 LoadBalance`load-balance`.*`http://www.gstatic.com/generate_204`300,,30
custom_proxy_group=✈️ Telegram`select`[]🚀 Selector`[]♻️ Url-Test`[]🚀 Switch`[]DIRECT
custom_proxy_group=🤖 OpenAI`select`[]🚀 Selector`[]♻️ Url-Test`[]🚀 Switch`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 Selector`[]♻️ Url-Test`[]🚀 Switch`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🚀 Selector`[]♻️ Url-Test`[]🚀 Switch`[]DIRECT
custom_proxy_group=📺 Bahamut`select`[]🇨🇳 Taiwan`[]🚀 Selector`[]🚀 Switch`[]DIRECT
custom_proxy_group=📺 Bilibili`select`[]🎯 Direct`[]🇨🇳 Taiwan`[]🇭🇰 Hong Kong`[]🚀 Selector
custom_proxy_group=🌍 GlobalMedias`select`[]🚀 Selector`[]♻️ Url-Test`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🌍 Europe`[]☁️ Cloudflare `[]🚀 Switch`[]DIRECT
custom_proxy_group=🌏 MediasCN`select`[]DIRECT`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🌍 Europe`[]🚀 Switch
custom_proxy_group=📢 GoogleFCM`select`[]DIRECT`[]🚀 Selector`[]🇺🇲 United States`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🌍 Europe`[]☁️ Cloudflare `[]🚀 Switch
custom_proxy_group=Ⓜ️ Bing`select`[]DIRECT`[]🚀 Selector`[]🇺🇲 United States`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🌍 Europe`[]☁️ Cloudflare `[]🚀 Switch
custom_proxy_group=Ⓜ️ OneDrive`select`[]DIRECT`[]🚀 Selector`[]🇺🇲 United States`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🌍 Europe`[]☁️ Cloudflare `[]🚀 Switch
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🚀 Selector`[]🇺🇲 United States`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🌍 Europe`[]☁️ Cloudflare `[]🚀 Switch
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 Selector`[]🇺🇲 United States`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🌍 Europe`[]☁️ Cloudflare `[]🚀 Switch
custom_proxy_group=🎮 Steam`select`[]DIRECT`[]🚀 Selector`[]🇺🇲 United States`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🌍 Europe`[]☁️ Cloudflare `[]🚀 Switch
custom_proxy_group=🎶 NeteaseMusic`select`[]DIRECT`[]🚀 Selector`[]♻️ Url-Test`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 Direct`select`[]DIRECT`[]🚀 Selector`[]♻️ Url-Test`[]🚀 Switch
custom_proxy_group=🛑 AdBlock`select`[]REJECT`[]DIRECT`[]🚀 Selector`[]🚀 Switch
custom_proxy_group=🍃 AppAdBlock`select`[]REJECT`[]DIRECT`[]🚀 Selector`[]🚀 Switch
custom_proxy_group=🐟 Final`select`[]DIRECT`[]🚀 Selector`[]♻️ Url-Test`[]🇭🇰 Hong Kong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🌍 Europe`[]🚀 Switch
custom_proxy_group=🌐 WestData`select`(西部数据|WestData|westdata|西数)
custom_proxy_group=🌸 FlowerCloud`select`(FlowerCloud|flowercloud|实验性|标准|高级|花云)
custom_proxy_group=🇭🇰 Hong Kong`url-test`(港|香港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`600,,15
custom_proxy_group=🇯🇵 Japan`url-test`(日本|Japan|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|jp)`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇺🇲 United States`url-test`(美|United States|美利坚|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|USA|America)`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🇨🇳 Taiwan`url-test`(台湾|台|新北|彰化|TW|tw|Taiwan|TaiWan)`http://www.gstatic.com/generate_204`600,,15
custom_proxy_group=🇸🇬 Singapore`url-test`(新加坡|狮城|Singapore|坡|Singapore|SG|Singapore|sg)`http://www.gstatic.com/generate_204`600,,20
custom_proxy_group=🇰🇷 Korea`url-test`(韩国|KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`600,,35
custom_proxy_group=🌍 Europe`url-test`(德|DE|de|Germany|German|德国|Frankfurt|奥|AT|Austria|英|UK|GB|Britain|United Kingdom|UnitedKingdom|英国|法|FR|France|荷|NL|Netherlands|Holland|荷兰|意|IT|Italy|瑞士|CH|Switzerland|瑞典|SE|Sweden|挪威|NO|Norway|丹麦|DK|Denmark|芬兰|FI|Finland|波兰|PL|Poland|捷克|CZ|Czech|Europe|Europe|EU|欧洲|欧盟)`http://www.gstatic.com/generate_204`600,,65
custom_proxy_group=☁️ Cloudflare `url-test`(cloudflare|Cloudflare|cf|科赋税|worker|cfnew|优选|反代|proxyip|cmliu|marisa|kristi|cfst|CFnat|天成)`http://www.gstatic.com/generate_204`600,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
